version: '3'

services:
  jupyter:
    image: jupyter/datascience-notebook:lab-4.0.7
    container_name: jupyter_for_duckdb
    restart: always
    # Заменить volumes до двоеточия на свой или вовсе уберите указание volumes, но тогда все изменения будут внутри контейнера
    volumes:
      - /Users/i.korsakov/_code/:/home/jovyan/_code
    ports:
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "docker"
      NB_USER: "root"
      GRANT_SUDO: "yes"
  minio:
    image: minio/minio:RELEASE.2024-07-04T14-25-45Z
    restart: always
    volumes:
      - ./data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"